config/routes.rb
Rails.application.routes.draw do

  root :to => 'diagnose#index'
  get '/diagnose' => 'diagnose#index'
  get '/diagnose/:diagram_id' => 'diagnose#play'

  resources :diagrams do
    member do
      get "image"
    end
    resources :nodes, shallow: true do
      resources :lines, shallow: true
    end
  end
  devise_for :users
  
  get 'top/index'

end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :user
  belongs_to :diagram
  belongs_to :node
  belongs_to :next_node, :class_name => "Node", :foreign_key => "next_node_id"

  validates_presence_of :user
  validates_presence_of :diagram
  validates_presence_of :node

  validates :description, length: {minimum: 1, maximum: 1024}

  #next_node が同一 diagram であることを確認
  validate :next_node_diagram_must_be_same
  def next_node_diagram_must_be_same
    nn = Node.find_by_id(self.next_node_id)
    if nn.nil?
      errors.add(:next_node_id, "is not found")
    elsif nn.diagram_id != self.diagram_id
      errors.add(:next_node_id, "has not same parent diagram")
    end
  end

  # 変更前後の node, next_node について start, end フラグのチェック
  after_save do
    if self.node_id_changed?
      self.node.update_start_end
    end
    if self.next_node_id_changed?
      self.next_node.update_start_end
      if !self.next_node_id_was.nil?
        Node.find(self.next_node_id_was).update_start_end
      end
    end
  end
  after_destroy do
    self.node.update_start_end
    self.next_node.update_start_end
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_node, only: [:index, :new, :create]
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.where(user_id: current_user.id, diagram_id:@diagram.id, node_id:@node.id)
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)
    @line.user = current_user
    @line.diagram = @diagram
    @line.node = @node

    respond_to do |format|
      if @result = @line.valid?
        begin
          Line.transaction do
            @line.save!
          end
          format.html { redirect_to @line, notice: 'Line was successfully created.' }
          format.json { render :show, status: :created, location: @line }
          format.js
        rescue => e
          render :text => e.message
        end
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    @line.attributes = line_params
    respond_to do |format|
      if @result = @line.valid?
        begin
          Line.transaction do
            @line.save!
          end
          format.html { redirect_to @line, notice: 'Line was successfully updated.' }
          format.json { render :show, status: :ok, location: @line }
          format.js
        rescue => e
          render :text => e.message
        end
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    Line.transaction do
      @line.destroy!
    end
    respond_to do |format|
      format.html { redirect_to node_lines_url(@node), notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
      @node = @line.node
      @diagram = @node.diagram
      head :forbidden unless @line.user_id == current_user.id
    end

    def set_node
      @node = Node.find(params[:node_id])
      @diagram = @node.diagram
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:next_node_id, :description)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_error.html.haml
%ul
  - line.errors.full_messages.each do |msg|
    %li= msg

app/views/lines/_form.html.haml
= form_for @line, url: node_lines_path(@node) do |f|
  - if @line.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line.errors.count, "error")} prohibited this line from being saved:"
      %ul
        - @line.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :next_node_id
    = f.number_field :next_node_id
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/lines/_line_create_form.html.haml
%div{:id => "line_create_error_#{node.id}"}
%div{:class => "line_element"}
  \└
  - line = Line.new
  = form_for line, url: node_lines_path(node), method: "post", remote: true, html: {:class => "line_create_form"} do |f|
    = f.text_field :description, :placeholder => "description"
    = f.text_field :next_node_id, :placeholder => "next_node_id"
    = f.submit('Create Line')

app/views/lines/_line_element.html.haml
%div.line_element{:id => "line_element_#{line.id}"}
  %div{:id => "line_element_error_#{line.id}"}
  \└
  = form_for line, url: line_path(line), method: "patch", remote: true do |f|
    = f.text_field :description, :placeholder => "description"
    = f.text_field :next_node_id, :placeholder => "next_node_id"
    = f.submit('Update')
  = form_for line, url: line_path(line), method: "delete", remote: true do |f|
    = f.submit('Delete', data:{confirm: 'Are you sure?'})

app/views/lines/create.js.haml
- if @result
  :plain
    var elm = $("div#line_create_error_#{@node.id}");
    elm.before("#{escape_javascript( render partial: 'lines/line_element', locals: {:line => @line} )}");
    $('.line_create_form > input[type="text"]').val('');
- else
  :plain
    var elm = $("div#line_create_error_#{@node.id}");
    elm.empty();
    elm.append("#{escape_javascript( render partial: 'lines/error', locals: {:line => @line} )}");

app/views/lines/destroy.js.haml
:plain
  var elm = $("div#line_element_#{@line.id}");
  elm.remove();

app/views/lines/edit.html.haml
%h1 Editing line

= render 'form'

= link_to 'Show', @line
\|
= link_to 'Back', node_lines_path(@node)

app/views/lines/index.html.haml
%h1 Listing lines

%table
  %thead
    %tr
      %th User
      %th Diagram
      %th Node
      %th Next node
      %th Description
      %th
      %th
      %th

  %tbody
    - @lines.each do |line|
      %tr
        %td= line.user_id
        %td= line.diagram_id
        %td= line.node_id
        %td= line.next_node_id
        %td= line.description
        %td= link_to 'Show', line
        %td= link_to 'Edit', edit_line_path(line)
        %td= link_to 'Destroy', line, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line', new_node_line_path(@node)

app/views/lines/new.html.haml
%h1 New line

= render 'form'

= link_to 'Back', node_lines_path(@node)

app/views/lines/show.html.haml
%p#notice= notice

%p
  %b User:
  = @line.user_id
%p
  %b Diagram:
  = @line.diagram_id
%p
  %b Node:
  = @line.node_id
%p
  %b Next node:
  = @line.next_node_id
%p
  %b Description:
  = @line.description

= link_to 'Edit', edit_line_path(@line)
\|
= link_to 'Back', node_lines_path(@node)

app/views/lines/update.js.haml
- if @result
  :plain
    alert("Success!");
- else
  :plain
    var elm = $("div#line_element_error_#{@node.id}");
    elm.empty();
    elm.append("#{escape_javascript( render partial: 'lines/error', locals: {:line => @line} )}");