config/routes.rb
Rails.application.routes.draw do

  root :to => 'diagnose#index'
  get '/diagnose' => 'diagnose#index'
  get '/diagnose/:diagram_id' => 'diagnose#play'

  resources :diagrams do
    member do
      get "image"
    end
    resources :nodes, shallow: true do
      resources :lines, shallow: true
    end
  end
  devise_for :users
  
  get 'top/index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :user
  belongs_to :diagram
  has_many :lines, dependent: :restrict_with_error
  has_many :connected_lines, class_name: "Line", foreign_key: "next_node_id", dependent: :restrict_with_error

  validates_presence_of :user
  validates_presence_of :diagram

  validates :description, length: {minimum: 1, maximum: 1024}

  def update_start_end
    self.start = Line.where(next_node_id: self.id).size <= 0
    self.end = self.lines.count <= 0
    if self.changed?
      self.save
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_diagram, only: [:index, :new, :create]
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.includes(:lines).where(user_id: current_user.id, diagram_id: @diagram.id)
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)
    @node.user = current_user
    @node.diagram = @diagram

    respond_to do |format|
      if @result = @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
        format.js
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @result = @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    respond_to do |format|
      if @result = @node.destroy
        format.html { redirect_to diagram_nodes_url(@diagram), notice: 'Node was successfully destroyed.' }
        format.json { head :no_content }
        format.js
      else
        format.html { redirect_to diagram_nodes_url(@diagram), notice: 'Node was unsuccessfully destroyed.'  }
        format.json { render json: @node.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
      @diagram = @node.diagram
      head :forbidden unless @node.user_id == current_user.id
    end

    def set_diagram
      @diagram = Diagram.find(params[:diagram_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:description)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_error.html.haml
%ul
  - node.errors.full_messages.each do |msg|
    %li= msg

app/views/nodes/_form.html.haml
= form_for @node, url: diagram_nodes_path(@diagram) do |f|
  - if @node.errors.any?
    #error_explanation
      %h2= "#{pluralize(@node.errors.count, "error")} prohibited this node from being saved:"
      %ul
        - @node.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/nodes/_node_element.html.haml
%div.node_element{:id => "node_element_#{node.id}"}
  %div{:id => "node_element_error_#{node.id}"}
  %span= "node_id:#{node.id}"
  = form_for node, url: node_path(node), method: "patch", remote: true do |f|
    = f.text_field :description
    = f.submit('Update')
  = form_for node, url: node_path(node), method: "delete", remote: true do |f|
    = f.submit('Delete', data:{confirm: 'Are you sure?'})

app/views/nodes/create.js.haml
- if @result
  :plain
    var elm = $("div#node_create_error");
    elm.before('<div class="node_#{@node.id}"></div>');
    var parent = $("div.node_#{@node.id}");
    parent.append("#{escape_javascript( render partial: 'nodes/node_element', locals: {:node => @node} )}");
    parent.append("#{escape_javascript( render partial: 'lines/line_create_form', locals: {:node => @node} )}");
    $('.node_create_form > input[type="text"]').val('');
- else
  :plain
    var elm = $("div#node_create_error");
    elm.empty();
    elm.append("#{escape_javascript( render partial: 'nodes/error', locals: {:node => @node} )}");

app/views/nodes/destroy.js.haml
- if @result
  :plain
    $("div#node_element_#{@node.id}").remove();
    $(".node_#{@node.id}").remove();
- else
  :plain
    var elm = $("div#node_element_error_#{@node.id}");
    elm.empty();
    elm.append("#{escape_javascript( render partial: 'nodes/error', locals: {:node => @node} )}");

app/views/nodes/edit.html.haml
%h1 Editing node

= render 'form'

= link_to 'Show', @node
\|
= link_to 'Back', diagram_nodes_path(@diagram)

app/views/nodes/index.html.haml
%h1= @diagram.title
%p.text-muted= @diagram.description

%h2 Nodes
%div#node_container
  / node list
  - @nodes.each do |node|
    %div{:class => "node_#{node.id}"}
      = render partial: "nodes/node_element", locals: {:node => node}
      / line list
      - node.lines.each do |line|
        = render partial: "lines/line_element", locals: {:line => line}
      / line create
      = render partial: "lines/line_create_form", locals: {:node => node}
  /node create
  %div#node_create_error
  %div.node_element
    - node = Node.new
    = form_for node, url: diagram_nodes_path(@diagram), method: "post", remote: true, html: {:class => "node_create_form"} do |f|
      = f.text_field :description, :placeholder => "description"
      = f.submit('Create Node')

%div
  = link_to "image reload", "#", :id => "diagram_image_reload", :onclick => "return false"

%div
  = image_tag image_diagram_path(@diagram), :id => "diagram_image", :width => 640

:javascript
  $(document).ready(function(){
    console.log("image reloaded");
    $("#diagram_image_reload").click(function(){
      var timestamp = new Date().getTime();
      $("#diagram_image").attr("src", "/diagrams/#{@diagram.id}/image?" + timestamp);
    });
  });

app/views/nodes/new.html.haml
%h1 New node

= render 'form'

= link_to 'Back', new_diagram_node_path(@diagram)

app/views/nodes/show.html.haml
%p#notice= notice

%p
  %b User:
  = @node.user_id
%p
  %b Diagram:
  = @node.diagram.id
%p
  %b Description:
  = @node.description

= link_to 'Edit', edit_node_path(@node)
\|
= link_to 'Edit Lines', node_lines_path(@node)
\|
= link_to 'Back', diagram_nodes_path(@diagram)

app/views/nodes/update.js.haml
- if @result
  :plain
    alert("Success!");
- else
  :plain
    var elm = $("div#node_element_error_#{@node.id}");
    elm.empty();
    elm.append("#{escape_javascript( render partial: 'nodes/error', locals: {:node => @node} )}");