config/routes.rb
Rails.application.routes.draw do

  root :to => 'diagnose#index'
  get '/diagnose' => 'diagnose#index'
  get '/diagnose/:diagram_id' => 'diagnose#play'

  resources :diagrams do
    member do
      get "image"
    end
    resources :nodes, shallow: true do
      resources :lines, shallow: true
    end
  end
  devise_for :users
  
  get 'top/index'

end

app/models/diagram.rb
require 'gviz'

class Diagram < ActiveRecord::Base

  belongs_to :user
  has_many :nodes
  has_many :lines

  validates_presence_of :user

  validates :title, length: {minimum: 1, maximum: 255}
  validates :description, length: {minimum: 1, maximum: 1024}

  def get_dot
    diagram = self
    Graph do
      diagram.nodes.each do |node|
        id = "n#{node.id}".to_sym
        node id, {label:node.description.scan(/.{1,8}/).join('\l'), shape:"square", style:"rounded", fontname:"07やさしさゴシックボールド"}
      end
      diagram.lines.each do |line|
        id = "n#{line.node_id}_n#{line.next_node_id}".to_sym
        edge id, {label:line.description}
      end
    end
  end
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  require "open3"

  before_action :authenticate_user!
  before_action :set_diagram, only: [:show, :edit, :update, :destroy, :image]

  # GET /diagrams
  # GET /diagrams.json
  def index
    @diagrams = current_user.diagrams
  end

  # GET /diagrams/1
  # GET /diagrams/1.json
  def show
  end

  # GET /diagrams/new
  def new
    @diagram = Diagram.new
  end

  # GET /diagrams/1/edit
  def edit
  end

  # POST /diagrams
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(diagram_params)
    @diagram.user = current_user

    respond_to do |format|
      if @diagram.save
        format.html { redirect_to @diagram, notice: 'Diagram was successfully created.' }
        format.json { render :show, status: :created, location: @diagram }
      else
        format.html { render :new }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagrams/1
  # PATCH/PUT /diagrams/1.json
  def update
    respond_to do |format|
      if @diagram.update(diagram_params)
        format.html { redirect_to @diagram, notice: 'Diagram was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagram }
      else
        format.html { render :edit }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.json
  def destroy
    @diagram.destroy
    respond_to do |format|
      format.html { redirect_to diagrams_url, notice: 'Diagram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
    dot = @diagram.get_dot
    o, e, s = Open3.capture3("dot -T png", :stdin_data => dot.to_s)
    send_data o, :disposition => "inline", :type => "image/png"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagram
      @diagram = Diagram.find(params[:id])
      head :forbidden unless @diagram.user_id == current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagram_params
      params.require(:diagram).permit(:title, :description)
    end
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/views/diagrams/_form.html.haml
= form_for @diagram do |f|
  - if @diagram.errors.any?
    #error_explanation
      %h2= "#{pluralize(@diagram.errors.count, "error")} prohibited this diagram from being saved:"
      %ul
        - @diagram.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/diagrams/edit.html.haml
%h1 Editing diagram

= render 'form'

= link_to 'Show', @diagram
\|
= link_to 'Back', diagrams_path

app/views/diagrams/index.html.haml
%h1 Listing diagrams

%table
  %thead
    %tr
      %th User
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @diagrams.each do |diagram|
      %tr
        %td= diagram.user_id
        %td= diagram.title
        %td= diagram.description
        %td= link_to 'Show', diagram
        %td= link_to 'Edit', edit_diagram_path(diagram)
        %td= link_to 'Destroy', diagram, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Diagram', new_diagram_path

app/views/diagrams/new.html.haml
%h1 New diagram

= render 'form'

= link_to 'Back', diagrams_path

app/views/diagrams/show.html.haml
%p#notice= notice

%p
  %b User:
  = @diagram.user_id
%p
  %b Title:
  = @diagram.title
%p
  %b Description:
  = @diagram.description

= link_to 'Edit', edit_diagram_path(@diagram)
\|
= link_to 'Edit Nodes', diagram_nodes_path(@diagram)
\|
= link_to 'Back', diagrams_path